# Generated by Django 5.0.1 on 2024-01-25 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_telegramuser_city_telegramuser_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramAds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Изображение рекламы.', null=True, upload_to='telegram_ads_image', verbose_name='Изображение')),
                ('text', models.TextField(blank=True, help_text='Текст рекламы.', null=True, verbose_name='Текст')),
                ('url', models.URLField(blank=True, help_text='Ссылка на рекламе.', null=True, verbose_name='Ссылка')),
                ('url2', models.URLField(blank=True, help_text='Ссылка 2 на рекламе.', null=True, verbose_name='Ссылка')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Временная метка, указывающая, когда была создана реклама.', verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Реклама Telegram',
                'verbose_name_plural': 'Рекламы Telegram',
                'ordering': ['-created_at'],
            },
        ),
    ]
